version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/html
    environment:
      DB_HOST: db
      DB_USERNAME: flow_order
      DB_PASSWORD: your_password
      DB_SCHEMA: flow_order
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: flow_order
      MYSQL_USER: flow_order
      MYSQL_PASSWORD: your_user_password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: